# Generated by Django 3.2.4 on 2021-06-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fakenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
